#!/usr/bin/python
# vim: set fileencoding=<utf_8> :

definitions = {
    "மற்றும்": "and",
    "தானியங்கி": "auto",
    "முறி":"break",
    "நிகழ்வு":"case",
    "எழுத்து":"char",
    "மாறாத":"const",
    "தொடர்":"continue",
    "இயல்பு":"default",
    "செய்":"do",
    "இரட்டை":"double",
    "வேறு":"else",
    "முடிவு":"end",
    "கணக்கீடு":"enum",
    "வெளிப்புற":"extern",
    "புள்ளி எண்":"float",
    "ஆக":"for",
    "செயல்":"function",
    "செல்":"goto",
    "என்றால்":"if",
    "முழு எண்":"int",
    "பெரிய":"long",
    "இல்லை":"not",
    "அல்லது":"or",
    "அச்சு":"print",
    "பதிவு":"register",
    "திரும்பு":"return",
    "சிறிய":"short",
    "குறியிட்ட":"signed",
    "அளவு":"sizeof",
    "நிலையான":"static",
    "அமைப்பு":"struct",
    "மாற்று":"switch",
    "வகை வரையறை":"typedef",
    "ஒற்றுமை":"union",
    "குறியற்ற":"unsigned",
    "மாறி":"variable",
    "வெறுமை":"void",
    "நிலையற்ற":"volatile",
    "இருப்பின்":"while"
}

print(definitions["புள்ளி எண்"])